### PR TITLE
Environment for Posix implemented - first comments appreciated

### PR DESCRIPTION
**Pull request by leutloff**
This is not really a pull request, but rather a request for comment.

I have implemented the Posix side of the environment.

I have the following questions:

1) Is the interface used the desired one? Examples are found in environment_test.cpp.

2) I would like to have test case with really setting the environment variables. The related test case is named set_environment_variables in environment_test.cpp. But I am not able to get the output from the launched application, because it does not compile. Do you have any hints? My try is commented out so that the actual code is working.

3) The actual implementation sets all the environment variables of the parent. Is this intentional? My new implementation is setting only the requested/provided environment variables.

Remark: My master branch uses patches from other development branches, too, e.g. with some test cases. Hmm I am a bit puzzeled because not only the changes on the new branch environment is chown 8-( but i ran out of time ...

### CODE REVIEW

**Comment by Shumen** [comment]
Hi, Christian, I've already upgraded boost-process to version 0.5 in my fork, the new version library supports Environment feature. I've only tested the posix side, however.

**Comment by leutloff** [comment]
Thank you for the feedback. The Windows side is not implemented at all so far. I hope to get feedback from Jeff, before continuing with the Windows side ...

**Comment by JeffFlinn** [comment]
Hi Christian,

Promise to get you feedback this evening after work.

Jeff

On Tue, Oct 9, 2012 at 9:46 AM, Christian Leutloff <notifications@github.com

**Comment by leutloff** [comment]
That is good news. The Windows side is now implemented, too. But not really setting the environment is not working, read crashing - so for now the new implementation is ignored and the existing one is used for windows. I will move the windows side to wstring and try to fix the implementation in the next days. The not working implementation is based on that of version 0.4.

**Comment by leutloff** [comment]
@JeffFlinn: Will you work on this library, again?

**Comment by JeffFlinn** [comment]
Hello Christian,

Funny I've just been thinking about boost process... I've been away from it
for a while. What are your thoughts about it?

Jeff

**Comment by leutloff** [comment]
Hello Jeff,

I really like the library. I am very sad that it is not more widely used. I am wondering why!?

I am using it very happily for my web application: https://github.com/leutloff/bergcms

The program maker is calling several other programs, like a perl script, pdflatex, bibtex, etc. The output of these programs is shown in the generated web page. The program was originally a shell script. This is still visible in the program: https://github.com/leutloff/bergcms/blob/master/src/srv/maker/maker.cpp

I would be very glad if you could merge the two or three different forks back into your main branch.

Yours
Christian

**Comment by leutloff** [comment]
Superceded by official integration into boost.

**Pull request closed without merging**
